name: Publish Pact Files
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pact
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: yarn install --immutable
      - run: yarn test
      - uses: jangjunha/pact-broker-actions/publish@main
        with:
          version: ${{ github.sha }}
          broker_url: ${{ vars.PACT_BROKER_URL }}
          broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
          broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
